# my config
version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: bnnguyen/react-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      #- docker/check:
          #docker-username: <username in environment variables inside circleci settings>
          #docker-password: <password in environment variables inside circleci settings>
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment

      - add_ssh_keys:
          fingerprints:
            - "e6:ed:1e:54:6c:e9:60:b1:42:e0:d9:73:b0:b7:d3:3d"
      - run: ssh -oStrictHostKeyChecking=no circleci@138.197.145.50 './deploy.sh'

      #- add_ssh_keys:
      #    fingerprints:
      #      - $SSH_KEY_FINGERPRINT
      #- run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER './deploy.sh'

workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - main
      # uncomment the 3 following lines to enable deploying
      - deploy:
          requires:
            - build-and-push